# Generated by Django 4.2 on 2023-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='approval_status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
