# Generated by Django 4.1.7 on 2023-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_leave_application_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
